# Generated by Django 3.2.6 on 2021-09-30 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrabble', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scrabble',
        ),
    ]
